language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
notifications:
  email:
    recipients:
      - huangzhen9706@gmail.com
    on_success: always
    on_failure: always
script:
  - npm test
  - unset CI 
  - npm run build
